### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by jayaramg-0** [LakshayD02/Project-Management-System#1]
I am trying to login with you gave username and password but unable to login.
the error message is "Error to log in ".
![Uploading Screenshot (8).png…]()

**Comment by LakshayD02** [comment]
> I am trying to login with you gave username and password but unable to login.
> the error message is "Error to log in ".
> ![Uploading Screenshot (8).png…]()
> 

Try with

Username - Lakshay
Password - Lakshay
